### ISSUE TITLE
Usability suggestion for C-n t and C-n T

### ISSUE THREAD

**Issue by sebasmonia** [julienXX/dotnet.el#4]
I think it would be better if `C-n t` asked which tests to run the first time and from there on acted like `C-n T`.
And if you want to run a different test command, then you can get queried again with `C-n T`.
It feels more natural/emacsy.

Another option which is even more Emacs-like would be to have `C-n t` query the first time, then re-run, and use a prefix arg to get queried again. `C-u C-n t` would make you provide the project again.

If you agree with the suggestion, I can provide a pull request with either change.
There's nothing wrong with the way it works now, that's why I'm checking for your thoughts before coding anything.

**Comment by julienXX** [comment]
Hi @sebasmonia that's a great suggestion, if you want to open a PR for it that would be excellent!
